### ISSUE TITLE
traefik login issue 

### ISSUE THREAD

**Issue by gzbenson** [heyValdemar/confluence-traefik-letsencrypt-docker-compose#2]
I used my own usename and password to gen. the new string(https://hostingcanada.org/htpasswd-generator/ ) and replaced traefikadmin:xxxxxxxxxxxxxxxxxx in the .env 
but i found that i could not login traefik.xxx.xxx.com by my name and password  , Is there any way to change the login password for traefik ?

**Comment by heyvaldemar** [comment]
hey @gzbenson,

To escape the `$` character in a string, you need to add an additional `$` before each occurrence. This results in `$$` for each `$` in the original string.

For example, the string `TRAEFIK_BASIC_AUTH=traefikadmin:$2y$10$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO` should be modified to `TRAEFIK_BASIC_AUTH=traefikadmin:$$2y$$10$$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO` to correctly escape the `$` characters.

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
